# Numpy - Tutorial 2

In [104]:
import numpy as np

## Subsetting/Slicing ndarray

In [135]:
arr = np.array([
    [1,3,5,7],
    [2,4,6,8],
    [1,2,3,4]
])

In [136]:
# Indexing row and slicing column
print(arr[0][1:3])
print(arr[1][2:])
print(arr[2][:3])

# Slicing rows 
print(arr[:2])
print(arr[1:])

# Slicing row and columns
print(arr[:2, 1:3])

[3 5]
[6 8]
[1 2 3]
[[1 3 5 7]
 [2 4 6 8]]
[[2 4 6 8]
 [1 2 3 4]]
[[3 5]
 [4 6]]


In [138]:
arr.dtype

dtype('int32')

## Type casting

 means changing the data type of elements in numpy array

.astype() --> Creates the copy of an array, it means that it does not modify the original array

In [139]:
arr.astype(np.float32)

array([[1., 3., 5., 7.],
       [2., 4., 6., 8.],
       [1., 2., 3., 4.]], dtype=float32)

In [140]:
arr

array([[1, 3, 5, 7],
       [2, 4, 6, 8],
       [1, 2, 3, 4]])

In [141]:
arr.dtype

dtype('int32')

In [143]:
# convert array elements to float

new_arr = arr.astype(np.float32)
print(new_arr.dtype)
print(new_arr)

float32
[[1. 3. 5. 7.]
 [2. 4. 6. 8.]
 [1. 2. 3. 4.]]


In [110]:
# convert array elements to string

#new_arr_str = arr.astype(np.string_)
new_arr_str = arr.astype(str)
print(new_arr_str.dtype)
print(new_arr_str)

<U11
[['1' '3' '5' '7']
 ['2' '4' '6' '8']
 ['1' '2' '3' '4']]


## Built-in array Generation functions: 

### Creating array of zeros

In [144]:
zeros = np.zeros((3,3))   # default data type is float

print(zeros)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [145]:
zeros.dtype

dtype('float64')

In [146]:
# type casting
new_zeros = zeros.astype(int)
print(new_zeros)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [113]:
# specifying dtype while creating array
zeros = np.zeros((3,3), dtype=np.int32)  
print(zeros)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [147]:
zeros_1 = np.zeros((4))
zeros_2 = np.zeros((4,5))

In [152]:
zeros_1.ndim

1

In [148]:
zeros_1

array([0., 0., 0., 0.])

In [154]:
zeros_2.ndim

2

In [149]:
zeros_2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Creating array of ones

In [115]:
ones = np.ones((3,4))

print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Creating identity matrix

In [155]:
# create 3x3 matrix
identity = np.eye(3)

print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [156]:
# creating 3x5 Identity matrix
identity = np.eye(3,5)

print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


### Creating array of constant values

In [157]:
array = np.full((3,3), 10)

print(array)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


### Creating array of random values

In [158]:
random_array = np.random.randint(0, 100, size=1000)
print(random_array)

[ 1 67  1 35 41 74 54 30 41 13 23 35 12 36 84 42  9 59 26 64 78 46 89 53
 16 95 30 93 75  7 71 89 85 36 79 95 23 65 68 23 94 95 77  1 63 62 25 73
 47 15 87 86 14 70 93 34 15 43  6 42 95 88 81 52 40 28 56 63  8 22 32 86
 37 80 78  9 15 60 61 17 86 66 79 74 82 91 59 86 40 26 91 70 63 40 14 30
 62 91  3  4 76  1 77 80 75 46 84 24 37 25  5 11 30 46 97 40 73 56 64 70
 35 81 83 26 80 13 74 94 23 13 46 79 84 76  5 12 83 48 85 49 89 74 60 54
 24 79 76 53 26 30 25 73 34 98 41 75 25 16 67 51 28 35 56 87 94 21 25 10
  9 44 30 81 39 97 95 95 60 45 13 36 14 52 76 83 94 54  6 48 86 50 27 69
 94 59 99 27 91 39 67 15 85  3 65 20 39 15 22 13  9 15 94 10 82 34 62 17
 55 46 56 34 52 98 99 60 81 43 45  1 36 65 34 51  5 75 17 21 77 46 75 79
 70 35 62 64 98 74 43 29 15  0 61 62 15 62 12  6 33 24 15 20 43 74 70 46
 35 31  6 22 86 56 41  7 56 96 90 83 96 98 18 11 44 80 52 62 70 12 45 18
 43 50 53 66 84  1 79 44 54 15 49 12 49 23 51 33 27  2  2 47 80 65 79 49
 77 29 55 76 39 51 24 45 81 51 56 77 13 93 33 31 98

In [159]:
random_array = np.random.randint(2,10, size=(3,3))

print(random_array)

[[5 9 5]
 [8 5 2]
 [2 3 7]]



## Vectorization

Vectorization means to perform mathematical operation on entire vectors or matrices at once, instead of looping through elements

In [123]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([2,3,4,5,6])

In [124]:
# element-wise operations (addition, subtraction, multiply, divide)
add_arr = arr1 + arr2
print(add_arr)
sub_arr = arr1 - arr2
print(sub_arr)
mul_arr = arr1 * arr2
print(mul_arr)
div_arr = arr1 / arr2
print(div_arr)

[ 3  5  7  9 11]
[-1 -1 -1 -1 -1]
[ 2  6 12 20 30]
[0.5        0.66666667 0.75       0.8        0.83333333]


In [125]:
arr = np.random.randint(0, 1000, size=(1000,1000))
new_arr = np.sin(arr)
print(new_arr)

[[-7.02450696e-01 -9.36461974e-01  6.96015201e-01 ...  6.02887067e-05
  -9.36461974e-01  7.62538949e-01]
 [-1.84811370e-01 -9.51073282e-01 -2.62403942e-01 ... -7.33169821e-01
  -7.51007151e-01  1.23513296e-01]
 [-5.31136890e-02  9.70542547e-01 -9.23481578e-01 ...  8.36655639e-01
  -5.73357175e-01  5.80611184e-01]
 ...
 [-3.38248293e-01 -7.14834271e-01  5.51401534e-01 ...  4.75576704e-01
  -9.81940765e-01 -9.05591148e-01]
 [-7.06920983e-02 -9.90611477e-01 -2.27993559e-01 ...  3.46649455e-01
   8.46188279e-01 -9.23458447e-01]
 [-5.29057106e-01 -7.90414741e-01  1.41120008e-01 ... -9.98345361e-01
   2.28022909e-01  5.21602441e-01]]


## Broadcasting   (Explained)

Broadcasting is the ability of Numpy to perform arithmetic operations on arrays of different shapes - by automatically expanding the smaller array so that it matches the shape of the larger one

General broadcasting rules
When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimension and works its way left. Two dimensions are compatible when

they are equal, or

one of them is 1.

If these conditions are not met, a ValueError: operands could not be broadcast together exception is thrown, indicating that the arrays have incompatible shapes.

Input arrays do not need to have the same number of dimensions. The resulting array will have the same number of dimensions as the input array with the greatest number of dimensions, where the size of each dimension is the largest size of the corresponding dimension among the input arrays. Note that missing dimensions are assumed to have size one.

### Example 1:  Scalar broadcasting

In [126]:
# Scalar broadcasting

arr = np.array([1,3,5,7])  # shape --> (4,)    or     1x4
# numpy automatically broadcast the scaler 5 to [5,5,5,5] before addition
print(arr + 5)

[ 6  8 10 12]


| Step                                   | Description                                                                  | Example in this case   |
| -------------------------------------- | ---------------------------------------------------------------------------- | ---------------------- |
| **1️⃣ Identify shapes**                | `arr` has shape `(4,)`, scalar `5` has shape `()`                            | `(4,)` and `()`        |
| **2️⃣ Align shapes (right to left)**   | NumPy lines them up: <br>`(4,)`<br>`()` → treat scalar as `(1,)`             | `(4,)` and `(1,)`      |
| **3️⃣ Apply compatibility rule**       | Dimensions are **compatible** if: <br>• same value OR <br>• one of them is 1 | `4` vs `1` ✅ compatible     |
| **4️⃣ Expand smaller shape**           | NumPy *virtually* expands scalar `(1,)` → `(4,)`                             | scalar → `[5,5,5,5]`   |
| **5️⃣ Perform element-wise operation** | Adds each element                                                            | `[1+5, 3+5, 5+5, 7+5]` |


### Row Broadcasting:

In [161]:
# Row broadcasting
arr1 = np.array([
    [1,2,3,4,5],
    [11,22,33,44,55]
])      # (2,5)
arr2 = np.array([2,3,4,5,6])   # (1,5)   --> (5,)

new_arr = arr1 + arr2
print(new_arr)

#(2,5)
#(1,5)

#[2,3,4,5,6]
#[2,3,4,5,6]

[[ 3  5  7  9 11]
 [13 25 37 49 61]]


| Step                                  | Description                                                                                              | Example in this case                             |
| ------------------------------------- | -------------------------------------------------------------------------------------------------------- | ------------------------------------------------ |
| **1️⃣ Identify shapes**               | `arr1` → `(2, 5)`  (2 rows × 5 columns)  <br>`arr2` → `(5,)`  (1D array)                                 | `(2, 5)` and `(5,)`                              |
| **2️⃣ Align shapes (right to left)**  | NumPy lines them up like this:<br>`(2, 5)`<br>    `(   5)`                                               | Missing dimension in `arr2` becomes 1 → `(1, 5)` |
| **3️⃣ Apply compatibility rule**      | Compare each dimension **from right to left:** <br>→ `5 vs 5` ✅ (equal) <br>→ `2 vs 1` ✅ (1 can stretch) | ✅ Compatible                                     |
| **4️⃣ Expand smaller array**          | NumPy virtually expands `arr2` into **two rows**: <br>`[[2,3,4,5,6], [2,3,4,5,6]]`                       | Now both `(2,5)`                                 |
| **5️⃣ Perform element-wise addition** | Adds each element positionally                                                                           | Works across both rows                           |


### Column Broadcasting

In [162]:
# column broadcasting
arr1 = np.array([
    [1,2,3,4],
    [2,3,4,5]
])   # (2,4)

arr2 = np.array([
    [2],
    [5]
])  # (2,1)

new_arr = arr1 + arr2
print(new_arr)

#(2,4)
#(2,1)

#[2,2,2,2]
#[5,5,5,5]


[[ 3  4  5  6]
 [ 7  8  9 10]]


| Step                                  | Description                                                                                         | Example in this case  |
| ------------------------------------- | --------------------------------------------------------------------------------------------------- | --------------------- |
| **1️⃣ Identify shapes**               | `arr1` → `(2, 4)`  <br>`arr2` → `(2, 1)`                                                            | `(2, 4)` and `(2, 1)` |
| **2️⃣ Align shapes (right to left)**  | Compare each dimension from **right → left**: <br>`4 vs 1` ✅ (1 can stretch) <br>`2 vs 2` ✅ (equal) | ✅ Compatible          |
| **3️⃣ Expand smaller array**          | NumPy **stretches** `arr2` horizontally across 4 columns:  <br>`[[2,2,2,2], [5,5,5,5]]`             | Now both `(2,4)`      |
| **4️⃣ Perform element-wise addition** | Each row of `arr1` adds with its corresponding broadcasted row from `arr2`                          | Works perfectly       |


### Arrays with Incompatible shapes

In [163]:
# Row broadcasting
arr1 = np.array([
    [1,2,3,4,5],
    [11,22,33,44,55]
])    # (2,5)
arr2 = np.array([2,3,4,5])  # (1,4)

new_arr = arr1 + arr2
print(new_arr)

#(2,5)
#(1,4)

ValueError: operands could not be broadcast together with shapes (2,5) (4,) 

In [127]:
# Row broadcasting
arr1 = np.array([
    [1,2,3,4,5],
    [11,22,33,44,55]
])
arr2 = np.array([
    [2,3,4,5],
    [1,2,3,4]
])

new_arr = arr1 + arr2
print(new_arr)

ValueError: operands could not be broadcast together with shapes (2,5) (2,4) 

In [128]:
a = np.array([
    [1],
    [2],
    [3]
])

In [129]:
a.shape

(3, 1)

In [130]:
b = np.array([1,2,3])

In [131]:
b.shape

(3,)

In [134]:
b

array([1, 2, 3])

In [132]:
a+b

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])