# Numpy (Numerical Python) - Tutorial for Beginners

Numpy is a Python Library used for working with large numbers and arrays. It makes easy to perform mathematical and scientific computation quickly and efficiently.

1. Numpy provides multi-dimensional arrays, known as ndarray (n-dimensional array) for storing large amount of numerical data.
2. It is much faster than Python List because ot is optimized for numerical operations.
3. Numpy arrays are best for mathematical data ot large datasets.


# Importing Numpy Library

In [2]:
# If error while importing numpy then install numpy in notebook using this command
!pip install numpy

In [3]:
import numpy as np    # np is the popular alias given to numpy

# Power of Numpy

Suppose we have two lists namely List1 and List2 which contains the first 100,000 non-negative number, and we want to create a new list namely List3 whose ith element is List1[i] * List2[i]

1. Approch 1: With Python List

Note: %%time is a magic method used for calculating the execution time of the cell

Wall time: is the time required by process to complete the task

In [4]:
%%time

List1 = [i for i in range(100000)]
List2 = [i for i in range(100000)]

CPU times: total: 15.6 ms
Wall time: 11.3 ms


In [5]:
%%time
List3 = [List1[i]*List2[i ]for i in range(100000)]

CPU times: total: 31.2 ms
Wall time: 34.8 ms


2. Approach 2: Using Numpy arrays

In [6]:
%%time

List1 = np.arange(100000)
List2 = np.arange(100000)

CPU times: total: 0 ns
Wall time: 2.25 ms


In [7]:
%%time

List3 = List1 * List2

CPU times: total: 0 ns
Wall time: 1.69 ms


Conclusion: The results are 10 to 15 times faster and we could do tasks in fewer lines of code

Python is much slower due to the type checking and other ovehead needed to interpret code.
Numpy use optimized pre-compiled C code, and is able to avoid a lot of overhead introduced.

# What is an Array?

A numpy array is a grid of values, all of the same data *type*. The number of dimensions is the rank of the array. And the shape of an array is the tuple of integers giving the size of the array along each dimension.

Creating an array of five integers

In [8]:
a = np.array([1,3,5,7,9])
print(a)
print(a.itemsize)

[1 3 5 7 9]
4


In the above cell, ***itemsize*** is the attribute of numpy array, which tells the size (in bytes) of each element in an array. So Each integer element occupy 8 bytes in the memory

arange() --> Get an array of a range of values

In [9]:
# array with values from 0 to 9
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
# array with values from 3 to 9
arr = np.arange(3,10)
print(arr)

[3 4 5 6 7 8 9]


In [11]:
# array with values in range with step size
arr = np.arange(3, 20, 2)
print(arr)

[ 3  5  7  9 11 13 15 17 19]


Check size of an array

In [12]:
print(arr.size)

9


Get length of an array

In [13]:
print(len(arr))

9


Get shape of an array

In [14]:
print(arr.shape)

(9,)


Type of an array

In [15]:
print(type(arr))

<class 'numpy.ndarray'>


DataType of an array

In [16]:
print(arr.dtype)

int32


Commonly used Numpy DataTypes

| Data Type                  | What it Represents | Typical Use Case                                           |
| -------------------------- | ------------------ | ---------------------------------------------------------- |
| **int32**                  | 32-bit integer     | Whole numbers (counts, IDs, indexing)                      |
| **int64**                  | 64-bit integer     | Larger integers (big datasets, IDs)                        |
| **float32**                | 32-bit decimal     | Machine learning (saves memory, faster training on GPUs)   |
| **float64**                | 64-bit decimal     | Default for NumPy, scientific calculations, high precision |
| **bool**                   | True/False values  | Masks, conditions, filtering                               |
| **complex64 / complex128** | Complex numbers    | Advanced math, signal processing                           |
| **string\_**               | Text data          | Labels, categorical data (but pandas is preferred)         |


Changing dataTypes of numpy array

In [17]:
int_arr = np.array([2,4,6,8,10], dtype=np.int32)
float_arr = np.array([2,4,6,8,10], dtype=np.float64)

print(int_arr)
print(float_arr)

print(f"Integers array element bytes {int_arr.itemsize}")
print(f"Float array element bytes {float_arr.itemsize}")

print(int_arr.dtype)
print(float_arr.dtype)

[ 2  4  6  8 10]
[ 2.  4.  6.  8. 10.]
Integers array element bytes 4
Float array element bytes 8
int32
float64


Indexing an Array

In [18]:
arr = np.array([2,4,6,8,10,12,14,16,18,20])
print(arr)

[ 2  4  6  8 10 12 14 16 18 20]


In [19]:
# print 1st, 4th and last element
print(arr[0])
print(arr[3])
print(arr[9])   # same as arr[-1]  or arr[len(arr) -1]

2
8
20


In [20]:
len(arr)

10

Modify array element

In [21]:
arr[0] = 200
print(arr)

[200   4   6   8  10  12  14  16  18  20]


Slicing

In [22]:
arr

array([200,   4,   6,   8,  10,  12,  14,  16,  18,  20])

In [23]:
arr[2:5]

array([ 6,  8, 10])

# N-Dimensional Array

n-dimensional arrays of homogeneous data types are the fundamental datatype used in Numpy. As these arrays are of fixed size of creation, they offers less flexibility than Python List, but can be more efficient runtime and memory-wise.

Rank of an Array:

The number of dimensions is the rank of ther array

In [32]:
# 1D array or Rank-1 array
oneD_array = np.array([2,3,4,5,6,79])

# dimensions of array
print(oneD_array.ndim)

# shape of array
print(oneD_array.shape)

# size of array
print(oneD_array.size)

1
(6,)
6


In [33]:
# 2D array (matrix) - Rank2 array
twoD_array = np.array([
    [2,3,5],
    [4,5,6]
])

# dimensions of array
print(twoD_array.ndim)

# shape of arrat
print(twoD_array.shape)   # return rows and columns

twoD_array

2
(2, 3)


array([[2, 3, 5],
       [4, 5, 6]])

Indexing in 2D array:
As in List, the indexing in numpy array also starts with 0
you must specify row and than column

In [34]:
print(twoD_array[0,0])
print(twoD_array[0,1])
print(twoD_array[0,2])

print(twoD_array[1,0])
print(twoD_array[1,1])
print(twoD_array[1,2])


2
3
5
4
5
6


In [35]:
# Alternatively we can also specify indexing in this way
print(twoD_array[0][0])
print(twoD_array[0][1])
print(twoD_array[0][2])

print(twoD_array[1][0])
print(twoD_array[1][1])
print(twoD_array[1][2])

2
3
5
4
5
6


In [40]:
# 3D array - Rank3 array  (3 axes)
# Axis 0 --> depth (number of blocks)
# Axis 1 --> rows
# Axis 2 --> columns


threeD_array = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

print(threeD_array.ndim)  

print(threeD_array.shape)

print(threeD_array)

3
(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
