# Numpy - Tutorial 3

## Note: In this tutorial we have covered topics till (Flatten and Ravel) - remaining topics we eill see in next class 

In [2]:
import numpy as np

## Reshape

changes the shape (dimensions) of numpy array without changing it data

In [22]:
# numpy arange() works similar to range() function of Python
# create an array with values are evenly spaced
arr = np.arange(10)    #c start --> 0, end --> 10-1 , step --> 1 (default)

print(arr)


[0 1 2 3 4 5 6 7 8 9]


In [23]:
arr.shape

(10,)

In [24]:
# Reshaping
new_arr_rshp1 = arr.reshape((2,5))
new_arr_rshp2 = arr.reshape((5,2))
#new_arr = arr.reshape((8,2))
#new_arr = arr.reshape((3,4))  # Error: cannot reshape array of size 10 into shape (3,4)


In [25]:
print(new_arr_rshp1)
print(new_arr_rshp1.shape)


[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)


In [26]:
print(new_arr_rshp2)
print(new_arr_rshp2.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
(5, 2)


reshape() returns a view (not a copy), so changing the reshaped array may affect the original

In [30]:
new_arr_rshp2[0][0] = 5

In [31]:
new_arr_rshp2

array([[5, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [32]:
arr

array([5, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Using -1 in reshape
When using -1 in reshape, then Numpy automatically calculates the dimension based on the size of array and the other dimension we have provides
Only one -1 is allowed in reshape


In [33]:
new_arr = arr.reshape((5,-1))

print(new_arr)
print(new_arr.shape)


[[5 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
(5, 2)


In [34]:
new_arr = arr.reshape((-1,5))

print(new_arr)
print(new_arr.shape)


[[5 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)


In [35]:
arr = np.array([
    [1,2,3,4,5],
    [6,7,8,9,0]
])

In [36]:
arr.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [37]:
arr

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

Note: Numpy supports object-oriented paradigm, so ndarray has number of methods and attributes, with functions similar to one in the Numpy outermost namespace


In [38]:
# Both implementations are valid
# implementation 1
print(np.min(new_arr))
# implementation 2
print(new_arr.min())


1
1


## Flatten and Ravel  
Flatten --> returns the copy of array collapsed into 1D. Changes to the flatten array not affect the original array

Ravel --> Returns the view of array in collapsed 1D. Changes to raveled array affect the original array


In [39]:
print(new_arr)
# Flatten()
flatten_arr = new_arr.flatten()
print(flatten_arr)
flatten_arr[0] = 100
print(flatten_arr)
print(new_arr)


[[5 1 2 3 4]
 [5 6 7 8 9]]
[5 1 2 3 4 5 6 7 8 9]
[100   1   2   3   4   5   6   7   8   9]
[[5 1 2 3 4]
 [5 6 7 8 9]]


In [40]:
# Ravel()
ravel_arr = new_arr.ravel()
print(ravel_arr)
ravel_arr[0] = 100
print(ravel_arr)
print(new_arr)


[5 1 2 3 4 5 6 7 8 9]
[100   1   2   3   4   5   6   7   8   9]
[[100   1   2   3   4]
 [  5   6   7   8   9]]


Array Operations
Numpy support various array operation, which are perfomed elementwise

In [41]:
arr = np.arange(2,19,2, dtype=np.float64)
x = arr.reshape((3,3))
y = np.full((3,3), 3, dtype=np.float64)
print(x)
print(y)


[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [42]:
# Addition
add = np.add(x,y)
print(add)
# subtraction
sub = np.subtract(x,y)
print(sub)
# multiply 
mul = np.multiply(x,y)
print(mul)
# divide
div = np.divide(x,y)
print(div)


[[ 5.  7.  9.]
 [11. 13. 15.]
 [17. 19. 21.]]
[[-1.  1.  3.]
 [ 5.  7.  9.]
 [11. 13. 15.]]
[[ 6. 12. 18.]
 [24. 30. 36.]
 [42. 48. 54.]]
[[0.66666667 1.33333333 2.        ]
 [2.66666667 3.33333333 4.        ]
 [4.66666667 5.33333333 6.        ]]


Numpy functions
There are also useful builtin functions of Numpy,  by using them we are able to express them across specific axes of the ndarray

axis = 0 --> Combines all rows and gives result per column  
axis = 1 --> Combines all columns and gives result per row

In [43]:
x = np.array([
    [1,2,4],
    [5,6,7]
])

print(np.sum(x))  # Compute sum all elements of x
print(np.sum(x, axis=0))  # Compute sum of each row
print(np.sum(x, axis=1))  # Compute sum of each column

25
[ 6  8 11]
[ 7 18]


In [44]:

print(np.min(x, axis=0))  
print(np.min(x, axis=1))
print(np.max(x, axis=0))
print(np.max(x, axis=1))


[1 2 4]
[1 5]
[5 6 7]
[4 7]


## argmax() 
compute index of max value in each row

In [45]:
print(np.argmax(x, axis=0))

[1 1 1]


Example: argmax()

In [46]:
students = np.array([
    [85, 92, 78],   # Student 1
    [88, 79, 95],   # Student 2
    [91, 94, 89]    # Student 3
])

# Best subject for each student
best_subjects = np.argmax(students, axis=1)
print("Best subject index for each student:", best_subjects)

# Best student in each subject
best_students = np.argmax(students, axis=0)
print("Best student index for each subject:", best_students)


Best subject index for each student: [1 2 1]
Best student index for each subject: [2 2 1]


In [47]:
#Numpy slicing
new_arr
new_arr[0:2, 0]  # for row 0 and row 1 take 1st colums
new_arr[:, 1:2]   # for all rows take 2nd colums

array([[1],
       [6]])

In [48]:
#Reversing an axis
new_arr
new_arr[0, ::-1]

array([  4,   3,   2,   1, 100])

## Filtering

We can also use boolean mask. Suppose we want to all elements of array with value greater tha MAX to MAX

In [49]:
MAX = 5
x = np.array([1, 4, 10, -1, 15, 0, 5])
print(x > MAX)    # returns an array of TRUE and FALSE base on the condition

x[x > MAX] = MAX
print(x)

[False False  True False  True False False]
[ 1  4  5 -1  5  0  5]


## Stacking

Joins a sequence of an arrays along new axis

In [24]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [25]:
b = np.arange(10,19).reshape(3,3)
print(b)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [26]:
c = np.arange(20,29).reshape(3,3)
print(c)

[[20 21 22]
 [23 24 25]
 [26 27 28]]


### Horizontal stacking

In [27]:
h_stack = np.hstack((a,b,c))
print(h_stack)

[[ 0  1  2 10 11 12 20 21 22]
 [ 3  4  5 13 14 15 23 24 25]
 [ 6  7  8 16 17 18 26 27 28]]


### Vertical Stacking

In [28]:
v_stack = np.vstack((a, b, c))
print(v_stack)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [20 21 22]
 [23 24 25]
 [26 27 28]]


In [29]:
d = np.arange(3)
print(d)

[0 1 2]


In [30]:
v_stack_new = np.vstack((v_stack, d))
print(v_stack_new)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [20 21 22]
 [23 24 25]
 [26 27 28]
 [ 0  1  2]]


1D vector

THe problem with 1D vector is that you can not define them as row and columns vectors, so sometimes it may be better to define them in 2D

In [32]:
v = np.random.rand(5)
print(v)
print(v.shape)

[0.43447991 0.90348517 0.64479388 0.88999972 0.03553752]
(5,)


Row vector

In [33]:
v = np.random.rand(1,5)
print(v)
print(v.shape)

[[0.67515327 0.89835452 0.67432502 0.41065956 0.21130859]]
(1, 5)


Column vector

In [34]:
v = np.random.rand(5,1)
print(v)
print(v.shape)

[[0.07127223]
 [0.92144951]
 [0.87567702]
 [0.03567996]
 [0.77648874]]
(5, 1)


converting Python List to Numpy Array

In [35]:
pythonList = [1,2,3,4,5]
print(type(pythonList))
numpyArray = np.array(pythonList)
print(type(numpyArray))

<class 'list'>
<class 'numpy.ndarray'>
